apiVersion: apps/v1

kind: Deployment

metadata:

  name: demo

  labels:

    app: demo

spec:

  replicas: 1

  selector:

    matchLabels:

      app: demo

  template:

    metadata:

      labels:

        app: demo

    spec:

      containers:

      - name: demo

        image: 971076122335.dkr.ecr.us-west-1.amazonaws.com/demo:dotnet-app-ChangebuildNumber

        ports:

        - containerPort: 80
